### ISSUE TITLE
plaid-go#109 is backwards-incompatible

### ISSUE THREAD

**Issue by bmhatfield** [plaid/plaid-go#114]
Hello plaid-go authors! We recently did an update of some of our go modules, and noticed that https://github.com/plaid/plaid-go/pull/109 was backwards incompatible for our use-case.

In particular, we configure plaid-go by setting the environment as a configuration value string externally to our program. For development, we used "sandbox.plaid.com", and for production "production.plaid.com".

The result was that after updating, we hit a runtime error: 
`Post "production.plaid.com/item/public_token/exchange": unsupported protocol scheme ""`.

Simply updating our configuration values to include `https://` resolved the problem, however others may get bitten by this as well, so we wanted to make you aware, as the backwards incompatible change for this value was a surprise to us.

Thank you!

**Comment by nathankot** [comment]
Hi @bmhatfield - sorry about that! When I made my change in #109 I didn't account for potential users of this library passing the environment as a string rather than `plaid.Sandbox`, `plaid.Production` etc.

I hope this will be a rare occurrence, but I will make a patch to make our environments structs rather than strings so that this can be caught by the compiler

**Comment by ConradKurth** [comment]
We encountered this issue as well
