### ISSUE TITLE
Investment Price/Value/Quantity are stored as float32 instead of float64

### ISSUE THREAD

**Issue by nc-wittj** [plaid/plaid-go#192]
In Go, I've always preferred using `float64` over `float32`, especially for numbers where precision is important, like price, quantity, and value.

However, it appears this package always uses `float32` (and `NullableFloat32`). Is there a particular reason for using that instead of `float64`? Does the API guarantee that the numbers have only 32 bit precision? Or is it possible that by using this package there will be some precision loss?

**Comment by phoenixy1** [comment]
@cgfarmer4 I think we should probably fix this -- does it need to be fixed in the schema or can we fix it in the Go-specific configuration files? Fixing it in the schema seems quite fragile and potentially error prone...

**Comment by nc-wittj** [comment]
@phoenixy1 @cgfarmer4 any updates on this? It's currently a blocker for us to upgrade to the new Plaid Go client. Thanks!

**Comment by johndpope** [comment]
excuse quick question, but how can coerce nullablefloat32 to float32?

**Comment by phoenixy1** [comment]
@nc-wittj we conferred on this internally among a few teams and agreed it makes sense to fix. It's just a little complicated because it is a change that is breaking to the client libraries and would require a major versioning event. We also need to make sure we correctly identify all places in the API where it makes sense to do this change. No promises but I'm going to try and target it next week. It might happen a little later though.

**Comment by phoenixy1** [comment]
Just to give you guys an update on this, as of last week, I have a PR in progress -- I'm now just waiting on confirmation that it solves the problem for the Go client libraries, as well as a review from domain experts to confirm that I've flagged all the appropriate values that could potentially need this level of precision.

**Comment by phoenixy1** [comment]
Just to follow up -- we've determined that no values from the API should require more than 4 decimal places of precision to represent. Given this, we think the right place to fix this is probably at the Go library generation layer rather than the OpenAPI specification layer. We're taking a look at what this would involve.

**Comment by nc-wittj** [comment]
Hey @phoenixy1! Any updates on this? We're still using v7 of this package due to this issue mentioned above.

**Comment by phoenixy1** [comment]
@nc-wittj this turned out to be much more complicated to fix than we thought because it doesn't appear that this can be fixed via the template file, type mappings, or any other user-exposed configuration settings in the Go generator. Currently, we are working on various OpenAPI generation related improvements and fixes in Q1 and have this tentatively included as part of that project.

**Comment by nc-wittj** [comment]
@phoenixy1 Thanks for the update!

**Comment by vorpus** [comment]
Please try v2.1.0 which uses float64 for most numbers.

**Comment by nc-wittj** [comment]
v3 seems to work great, thanks!
