### ISSUE TITLE
NullableString still Null after saying it's set

### ISSUE THREAD

**Issue by edstef** [plaid/plaid-go#222]
Hi, I am using plaid-go V1.4.0 where we migrated all strings returned from Plaid to "Plaid.NullableString". I keep getting NPE's when trying to access the strings even though I am checking for IsSet.

My code:
```
 	if str.IsSet() {
		fmt.Println(*str)
	}

```

I added some logs to debug:
```
	fmt.Println(str.IsSet())
	fmt.Println(str.Get())
```
which returns
```
true
<nil>
```

Am I using this wrong by checking IsSet instead of something else? Thanks

update: I tried on v1.10 and the plaid library is still returning fake nullablestrings

**Comment by edstef** [comment]
I tried looking up the code in this repository that I used initially but I can't find it anymore

**Comment by edstef** [comment]
These strings that are null are from my API call resp.Transaction called like:

```
	resp, _, err := hdh.PlaidClient.PlaidApi.TransactionsGet(ctx).TransactionsGetRequest(*request).Execute()
	if err != nil {
            ...
	}
```

**Comment by jkoelker** [comment]
The problem is that `IsSet` is indicating that the value was set from the call, the value can still be `nil` however. This is the current pattern to "safely access the value":

```golang
transactionCode := ""
if txn.TransactionCode.IsSet() {
    code := txn.TransactionCode.Get()
    if code != nil {
        transactionCode = string(*code)
    }
}
```

Unfortunately this is coming from the swagger autogen wrapper, which is creating a very difficult api to use effectively. There is an issue in the generator https://github.com/OpenAPITools/openapi-generator/issues/8340 requesting a api change so it would behave as one would expect a `IsSet()` call to do ;).

**Comment by vorpus** [comment]
Thanks for the link to the OpenAPITools issue! I reproduced locally and this behavior definitely feels suboptimal :(

**Comment by vorpus** [comment]
@edstef could you try version 2.0.1 and see if this resolves the nullablestring problem? Thanks!

**Comment by vorpus** [comment]
(please reopen if this issue comes up again)
